### ISSUE TITLE
colab prediction error

### ISSUE THREAD

**Issue by pr4deepr** [kapoorlab/VollSeg#5]
Hi 
  I was running the colab prediction notebook on a 3D dataset with a model I trained using the Vollseg colab notebook.  I only used 20 epochs to get a model I can quickly test to see if everything works. 

When using the colab prediction notebook, I running into an error. 
`StarDist3D has no attribute predict_vollseg`

I think it has to do with this line, where there are duplicate imports:

https://github.com/Kapoorlabs-paris/VollSeg/blob/main/vollseg/helpers.py#L18-L19

I disabled the StarDist import as a test and it seemed to get rid of that error, but then I ran into another one:

```
Generating SmartSeed results
UNET segmentation on Image
Stardist segmentation on Image
Predicting Instances
2022-01-13 05:57:55.320840: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 585105408 exceeds 10% of free system memory.
Predictions Done
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_1835/4171433795.py in <module>
      7 for fname in filesRaw:
      8 
----> 9      SmartSeedPrediction3D(SaveDir, fname, UnetModel, StarModel,min_size = min_size,  n_tiles = n_tiles, UseProbability = True)#NoiseModel,

1 frames
/usr/local/lib/python3.7/dist-packages/vollseg/helpers.py in SmartSeedPrediction3D(SaveDir, fname, UnetModel, StarModel, NoiseModel, min_size_mask, min_size, max_size, n_tiles, UseProbability, globalthreshold, extent, dounet, seedpool, otsu, startZ)
    961     imwrite((UNETResults + Name+ '.tif' ) , SizedMask.astype('uint16'))
    962     print('Stardist segmentation on Image')
--> 963     SmartSeeds, ProbabilityMap, StarImage, Markers = STARPrediction3D(image, StarModel,  n_tiles, MaskImage = Mask, UseProbability = UseProbability, globalthreshold = globalthreshold, extent = extent, seedpool = seedpool)
    964 
    965     for i in range(0, SmartSeeds.shape[0]):

/usr/local/lib/python3.7/dist-packages/vollseg/helpers.py in STARPrediction3D(image, model, n_tiles, MaskImage, smartcorrection, UseProbability, globalthreshold, extent, seedpool, prob_thresh, nms_thresh)
   1261 
   1262     Probability = np.zeros([SmallProbability.shape[0] * grid[0],SmallProbability.shape[1] * grid[1], SmallProbability.shape[2] * grid[2] ])
-> 1263 
   1264     print('Reshaping')
   1265     #We only allow for the grid parameter to be 1 along the Z axis

IndexError: tuple index out of range
```

`SmallProbability ` seemed to be of shape (348,). 

Cheers
Pradeep

**Comment by kapoorlab** [comment]
Hi @pr4deepr, 

Thank you for reporting the error, it happened because I changed the predict function that VollSeg was calling and instead of returning the probability map it was returning a flattend map instead. This is however fixed in the latest release, 2.6.8 and I additionally made a function VollSeg3D that is called from Napari and now you can also call it from the [Colab notebook](https://github.com/Kapoorlabs-paris/VollSeg/blob/main/examples/Predict/ColabModelPrediction.ipynb) Can you please try this notebook and see if that works for you now. I will look into the other issue you are facing using it as a Napari plugin.
